import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";
import PushSubscriber from "@/components/PushSubscriber";
import {
  ClerkProvider
} from '@clerk/nextjs'
import AuthHeader from "@/components/AuthHeader";
import NavBar from "@/components/NavBar";


const rajdhani = Rajdhani({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-rajdhani",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${rajdhani.variable} font-rajdhani antialiased`}>
          <NavBar />
          <AuthHeader />
          <PushSubscriber />
          
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}

